### ISSUE TITLE
trace id 存储的问题

### ISSUE THREAD

**Issue by yuwingo** [e421083458/gin_scaffold#2]
您好 `c.Set`和`c.Value`在调用量很大的情况下，会产生同时读写map的问题吗

**Comment by e421083458** [comment]
不会有这个问题，context只会对当前一个会话有影响。并且context的vk存储使用的是链表方式。获取时是链式遍历的。不存在你说的map同时读写问题。

**Comment by yuwingo** [comment]
```
func RequestLog() gin.HandlerFunc {
	return func(c *gin.Context) {
		RequestInLog(c) // 里边实现了c.Set("trace", traceContext)
		defer RequestOutLog(c)
		c.Next()
	}
}
```

这个中间件每次请求都会生成一个gin.context，对于单次请求来说，我想要获取trace这个参数打印到日志中，我会c.Value("trace")，这时候有概率发生同时读写gin.Context这个struct中的Keys这个map

**Comment by e421083458** [comment]
如果频发发生多次key读写问题。可以自己封装一个方法，加一把锁。
