### ISSUE TITLE
trace_id 是变动的，mysql 的 和 request_in  和 request_out 的不一样

### ISSUE THREAD

**Issue by thinkeng** [e421083458/gin_scaffold#3]
[INFO][2020-01-06T15:37:34.204][log.go:58] _com_request_in||method=GET||body=||from=127.0.0.1||traceid=a9fe0fb65e12e3be9f4c1a90b62158b0||cspanid=||spanid=f7ecec083c04951a||uri=/demo/dao?id=1||args=map[]
[INFO][2020-01-06T15:37:34.204][log.go:58] _com_mysql_success||sql=SELECT * FROM `area`  WHERE (id = '1')||cspanid=||spanid=f7ecec0825845c95||source=D:/golang/gin_scaffold/dao/demo.go:24||current_time=2020-01-06 15:37:34||affected_row=0||traceid=a9fe0fb65e12e3be47941a903a768bb0||level=sql||proc_time=0.000000000
[INFO][2020-01-06T15:37:34.204][log.go:58] _com_request_out||proc_time=0.0029922||traceid=a9fe0fb65e12e3be9f4c1a90b62158b0||cspanid=||uri=/demo/dao?id=1||method=GET||args=map[]||from=127.0.0.1||response={\"errno\":0,\"errmsg\":\"\",\"data\":\"[]\",\"trace_id\":\"a9fe0fb65e12e3be9f4c1a90b62158b0\"}||spanid=f7ecec083c04951a

**Comment by e421083458** [comment]
之前代码没有传递ctx上下文，现在调整好了。

[INFO][2020-02-17T11:55:15.590][log.go:58] _com_request_in||cspanid=||method=GET||args=map[]||traceid=c0a803045e4a0ea37ee0fc98104dc7b0||spanid=9ee20da7380704bb||uri=/demo/dao?id=1||body=||from=127.0.0.1
[INFO][2020-02-17T11:55:15.590][log.go:58] _com_mysql_success||level=sql||affected_row=1||cspanid=||spanid=9ee20da7380704bb||source=/Users/niuyufu/go/src/git.xiaojukeji.com/cloud/its-service/signal-upm/dao/demo.go:25||current_time=2020-02-17 11:55:15||proc_time=0.000000000||sql=SELECT * FROM `area`  WHERE (id = '1')||traceid=c0a803045e4a0ea37ee0fc98104dc7b0
[INFO][2020-02-17T11:55:15.590][log.go:58] _com_request_out||uri=/demo/dao?id=1||args=map[]||from=127.0.0.1||proc_time=0.001729409||traceid=c0a803045e4a0ea37ee0fc98104dc7b0||cspanid=||method=GET||response={\"errno\":0,\"errmsg\":\"\",\"data\":\"[{\\\"id\\\":1,\\\"area_name\\\":\\\"area_name\\\",\\\"city_id\\\":1,\\\"user_id\\\":2,\\\"update_at\\\":\\\"2019-06-15T00:00:00+08:00\\\",\\\"create_at\\\":\\\"2019-06-15T00:00:00+08:00\\\",\\\"delete_at\\\":\\\"2019-06-15T00:00:00+08:00\\\"}]\",\"trace_id\":\"c0a803045e4a0ea37ee0fc98104dc7b0\"}||spanid=9ee20da7380704bb
