### ISSUE TITLE
session和jwt

### ISSUE THREAD

**Issue by xushuhui** [e421083458/gin_scaffold#5]
项目中的会话是通过session实现的，而现在前后端分离项目越来越多，为什么没考虑用jwt这种形式实现会话，这样通用性不是更好吗？

**Comment by xushuhui** [comment]
还有trace_id的作用是什么，为了保持接口请求幂等吗？

**Comment by e421083458** [comment]
1、目前定位是pc_web的会话。
2、trace_id，是为了做链路排查。

**Comment by congzhichao** [comment]
> jwt

我十分赞同你的说法，现在都用前后端，所以我觉得jwt比较好，我自己琢磨改进这个框架，但是确实有些地方跟作者的想法有出入，改起来比较费劲。
